extends RefCounted
class_name CssPartsCatalog

## Static CSS NC II parts encyclopedia shared by the dashboard search UI.

const ALL := "All"

const CATEGORIES: Array[String] = [
	ALL,
	"Core Hardware",
	"Tools and ESD",
	"Network Devices",
	"Cabling and Media",
	"Servers and Storage",
	"Internet and Cloud",
	"Peripherals",
	"Maintenance",
]


static func all_parts() -> Array[Dictionary]:
	return [
		_part("motherboard", "Motherboard", "Core Hardware",
			"Central board connecting CPU, RAM, storage, and peripherals.",
			"The motherboard is the main PCB holding the CPU socket, RAM slots, chipset, BIOS/UEFI, and I/O.",
			"Power and data routes run through the chipset. POST/BIOS initializes hardware before the OS loads.",
			"CSS Unit 1 technicians match form factor and socket type before assembly.",
			"No POST, bent pins, shorted standoffs, incompatible BIOS.",
			"Dry-fit standoffs before seating the CPU. Match holes to avoid shorts.",
			[0, 1], "res://assets/images/cards/card_motherboard.png"),
		_part("cpu", "CPU", "Core Hardware",
			"Processor that fetches, decodes, and executes instructions.",
			"The CPU is the main compute engine and requires proper cooling.",
			"Cores and cache improve multitasking; the memory controller talks to RAM.",
			"Verify socket compatibility and seat coolers without warping the board.",
			"Bent pins, missing paste, cooler not locked, overheating.",
			"Align the triangle marker. Never force the lever.",
			[0, 1], "res://assets/images/cards/card_cpu.png"),
		_part("ram", "Memory (RAM)", "Core Hardware",
			"High-speed temporary storage for active programs and OS data.",
			"RAM holds working data while the system runs; contents clear on power loss.",
			"Dual-channel kits improve bandwidth when installed in matched slots.",
			"Seat modules until both latches click; match DDR generation.",
			"Half-seated sticks, mixed kits, dirty contacts.",
			"Use motherboard-manual slots for dual-channel.",
			[0, 1], "res://assets/images/cards/card_ram.png"),
		_part("psu", "Power Supply (PSU)", "Core Hardware",
			"Converts AC wall power into DC rails for every component.",
			"Supplies +12V/+5V/+3.3V and standby power with matching connectors.",
			"Switching electronics regulate voltages; modular cables reduce clutter.",
			"Route cables safely and verify 24-pin plus CPU power.",
			"No power, overloaded rails, missing CPU power cable.",
			"Test with a known-good PSU before replacing boards.",
			[0, 1, 4], "res://assets/images/cards/card_psu.png"),
		_part("ssd", "SSD", "Core Hardware",
			"Fast solid-state storage for OS and applications.",
			"NAND flash with SATA or NVMe interfaces; no moving parts.",
			"Controllers manage wear leveling; NVMe uses PCIe lanes.",
			"Install OS media on SSD and confirm BIOS boot order.",
			"Drive not detected, missing M.2 screw, shared SATA/NVMe ports.",
			"Enable AHCI/NVMe as required after install.",
			[1], "res://assets/images/cards/card_storage.png"),
		_part("hdd", "Hard Disk Drive (HDD)", "Core Hardware",
			"Magnetic spinning storage for bulk data at lower cost per GB.",
			"Platters and a moving head; useful for backups and media libraries.",
			"Mechanical seeks add latency; SATA power/data connect to the board.",
			"Mount in cages and often pair with SSD boot volumes.",
			"Clicking, bad sectors, loose SATA power.",
			"Back up immediately if SMART reports reallocated sectors.",
			[1, 3, 4], "res://assets/images/cards/card_storage.png"),
		_part("gpu", "Graphics Card (GPU)", "Core Hardware",
			"Renders display output; optional discrete card for heavier workloads.",
			"Discrete GPUs install in PCIe x16 and need adequate PSU connectors.",
			"GPU processes frames and outputs via HDMI/DisplayPort.",
			"Confirm BIOS primary display for office vs design lab builds.",
			"No display, insufficient PCIe power, seating not locked.",
			"Try motherboard video before assuming GPU failure.",
			[1, 4], "res://assets/images/cards/card_expansion.png"),
		_part("nic", "Network Interface Card (NIC)", "Core Hardware",
			"Provides wired Ethernet connectivity to a host.",
			"Onboard or add-in adapter with a unique MAC address.",
			"Converts frames between the OS stack and Ethernet medium.",
			"Required for Module 2 IP config and file sharing tests.",
			"No link light, disabled adapter, damaged RJ45 latch.",
			"Check link lights before changing IP settings.",
			[1, 2], "res://assets/images/cards/card_network.png"),
		_part("case", "System Unit / Case", "Core Hardware",
			"Enclosure that mounts the board, drives, PSU, and cooling.",
			"Provides structure, airflow, front I/O, and drive bays.",
			"Intake/exhaust fans move air across heatsinks.",
			"Assembly order: prepare chassis, install PSU and board, route cables.",
			"Missing standoffs, blocked airflow, miswired front panel.",
			"Photograph front-panel pinouts before disconnecting.",
			[0, 1, 4], "res://assets/images/cards/card_system_unit.png"),
		_part("antistatic", "Anti-static Kit", "Tools and ESD",
			"Wrist strap and mat that protect boards from electrostatic discharge.",
			"ESD can silently damage ICs during handling.",
			"Strap equalizes potential between technician and grounded mat/chassis.",
			"Required before handling boards, CPU, RAM, or cards.",
			"Strap not grounded, working on carpet without a mat.",
			"Clip to bare metal—not painted surfaces.",
			[0, 1, 4], "res://assets/images/cards/card_safety.png"),
		_part("screwdriver_set", "Screwdriver Set", "Tools and ESD",
			"Precision drivers for case, motherboard, and drive screws.",
			"Phillips and hex bits cover most PC fasteners.",
			"Correct bit size prevents stripped heads.",
			"Daily CSS tooling for installs and maintenance.",
			"Stripped screws, lost M.2 screws, overtightening.",
			"Organize screws by type as you remove them.",
			[1, 4], "res://assets/images/cards/card_tools.png"),
		_part("cable_tester", "Cable Tester", "Tools and ESD",
			"Verifies pinout and continuity on Ethernet cables.",
			"Basic pair testers light each conductor end-to-end.",
			"Injector and remote map opens, shorts, and crosses.",
			"Essential after fabricating T568A/B cables.",
			"False fails from bad remotes; untested factory cables.",
			"Test every field-terminated cable and label both ends.",
			[2], "res://assets/images/cards/card_tools.png"),
		_part("router", "Router", "Network Devices",
			"Forwards packets between networks; often provides NAT/DHCP/Wi-Fi.",
			"Connects different IP networks—typically LAN to WAN/Internet.",
			"Routing tables decide next hops; NAT translates private addresses.",
			"Module 2: set gateway/DNS and verify Internet reachability.",
			"Double NAT, wrong WAN type, default passwords unchanged.",
			"Confirm WAN link lights first; document subnet settings.",
			[2], "res://assets/images/cards/card_network.png"),
		_part("switch", "Switch", "Network Devices",
			"Forwards Ethernet frames between devices in the same LAN.",
			"Expands wired ports and learns MAC addresses.",
			"Each port is a collision domain; unknown MACs are flooded.",
			"Interconnects PCs, APs, and servers in CSS lab topologies.",
			"No link, switching loops, PoE budget issues.",
			"Match cable category to desired speed; check port LEDs.",
			[2], "res://assets/images/cards/card_network.png"),
		_part("hub", "Hub", "Network Devices",
			"Legacy multiport repeater that shares one collision domain.",
			"Repeats bits to every port; largely obsolete versus switches.",
			"All devices share bandwidth; no MAC learning.",
			"Training contrast so trainees choose modern switches.",
			"Severe congestion and sniffing risk.",
			"Replace hubs during upgrades.",
			[2], "res://assets/images/cards/card_network.png"),
		_part("modem", "Modem", "Network Devices",
			"Converts ISP WAN signals for the LAN router.",
			"Edge device facing the ISP (DSL/cable/fiber ONT handoff).",
			"Demodulates provider medium into Ethernet/IP.",
			"Verify modem sync before blaming LAN configuration.",
			"No sync, ISP outage, bridged vs routed confusion.",
			"Power-cycle modem then router in order.",
			[2, 4], "res://assets/images/cards/card_network.png"),
		_part("access_point", "Access Point (AP)", "Network Devices",
			"Extends wireless coverage so Wi-Fi clients join the LAN.",
			"Bridges wireless clients onto wired Ethernet.",
			"Radios associate clients with WPA2/WPA3 security.",
			"Secure Wi-Fi and verify clients reach LAN and Internet.",
			"Weak signal, interference, wrong passphrase.",
			"Place APs high and clear of thick walls.",
			[2], "res://assets/images/cards/card_network.png"),
		_part("repeater", "Repeater / Extender", "Network Devices",
			"Regenerates a signal to extend wired or wireless reach.",
			"Wi-Fi extenders rebroadcast an SSID; copper/fiber repeaters clean long links.",
			"Receives a weak signal and retransmits a cleaned copy.",
			"Used when one AP cannot cover a lab or office.",
			"Half-speed links, poor placement too far from source.",
			"Prefer a second wired AP when cabling is possible.",
			[2, 4], "res://assets/images/cards/card_network.png"),
		_part("firewall", "Firewall", "Network Devices",
			"Filters traffic based on rules to protect hosts and networks.",
			"Hardware appliance or host software firewall.",
			"Rules evaluate addresses, ports, and connection state.",
			"Open only required ports for file sharing services.",
			"Blocked shares, overly permissive any-any rules.",
			"Document every rule change with the ticket.",
			[2, 3, 4], "res://assets/images/cards/card_hazard.png"),
		_part("ethernet_cable", "Ethernet Cable", "Cabling and Media",
			"Twisted-pair copper cable for LAN links (Cat5e/Cat6).",
			"UTP with RJ45; straight-through T568B is standard PC-to-switch.",
			"Twisting reduces crosstalk; length typically ≤100 m.",
			"Build and test straight-through and crossover cables.",
			"Open pairs, wrong pinout, damaged latch.",
			"Always continuity-test before deployment.",
			[2], "res://assets/images/cards/card_connector.png"),
		_part("fiber_optic", "Fiber Optic Cable", "Cabling and Media",
			"Glass/plastic strands that carry data as light.",
			"Resists EMI and supports long high-speed links.",
			"Transmitter converts to light; receiver converts back.",
			"Recognize fiber uplinks and handle connectors carefully.",
			"Dirty connectors, bent fiber, mismatched optics.",
			"Never look into live fiber; clean before mating.",
			[2, 4], "res://assets/images/cards/card_connector.png"),
		_part("patch_panel", "Patch Panel", "Cabling and Media",
			"Organizes horizontal cabling into labeled front ports.",
			"Terminates structured cabling from wall outlets.",
			"Rear punch-downs feed front RJ45 jacks for switch patching.",
			"Professional practice for neat LAN closets.",
			"Mislabeling, poor punch-downs, undocumented moves.",
			"Update the port map whenever you move a patch.",
			[2], "res://assets/images/cards/card_port.png"),
		_part("crimper", "RJ45 Crimper", "Cabling and Media",
			"Tool that terminates plugs onto Ethernet cable ends.",
			"Seats gold contacts onto conductors in T568 order.",
			"Die presses contacts and may strain-relieve the jacket.",
			"Hands-on Module 2 skill for patch cords.",
			"Wires not fully inserted, wrong sequence, incomplete crimp.",
			"Test every cable after crimping.",
			[2], "res://assets/images/cards/card_tools.png"),
		_part("file_server", "File Server", "Servers and Storage",
			"Central host that shares folders and manages user access.",
			"Stores department data and authenticates users/groups.",
			"SMB shares combine with NTFS/share permissions.",
			"Module 3: users, groups, folders, least privilege.",
			"Access denied, broken paths, firewall blocking SMB.",
			"Test with a standard user—not only admin.",
			[3], "res://assets/images/cards/card_system_unit.png"),
		_part("nas", "NAS Appliance", "Servers and Storage",
			"Dedicated network storage appliance for shared volumes.",
			"Simpler file services than a full server OS; often with RAID.",
			"Clients connect over Ethernet using SMB/NFS/web UI.",
			"Department volumes and backup targets in CSS scenarios.",
			"RAID degraded, full volumes, dirty shutdowns.",
			"Monitor disk health; update firmware in windows.",
			[3, 4], "res://assets/images/cards/card_storage.png"),
		_part("raid", "RAID Storage", "Servers and Storage",
			"Multiple disks combined for speed, redundancy, or both.",
			"Levels trade capacity for performance and fault tolerance.",
			"Controllers stripe/mirror; failed disks rebuild from parity/mirrors.",
			"Awareness when diagnosing server storage outages.",
			"Wrong disk pulled, RAID 0 single-disk loss.",
			"RAID is not a backup—keep off-array copies.",
			[3, 4], "res://assets/images/cards/card_storage.png"),
		_part("isp", "ISP / WAN Edge", "Internet and Cloud",
			"Internet Service Provider link that brings external connectivity.",
			"Boundary between the organization and the ISP demarc.",
			"Public IP, routing, and SLAs are provider-defined.",
			"Isolate LAN vs WAN faults in connectivity tickets.",
			"ISP outage, wrong PPPoE credentials, fiber cuts.",
			"Capture modem lights and public IP tests before calling ISP.",
			[2, 4], "res://assets/images/cards/card_growth.png"),
		_part("dns", "DNS", "Internet and Cloud",
			"Resolves human-readable names to IP addresses.",
			"Translates names like example.com into routable IPs.",
			"Clients query resolvers; authoritative servers answer zones.",
			"IP setup includes correct DNS—gateway or public resolvers.",
			"Wrong DNS IP, offline resolver, cached bad records.",
			"Ping by IP vs hostname to separate DNS from routing.",
			[2, 3], "res://assets/images/cards/card_network.png"),
		_part("cloud_storage", "Cloud Storage", "Internet and Cloud",
			"Off-site file storage accessed over the Internet.",
			"Providers host files in remote data centers.",
			"Data travels over HTTPS; local caches may keep copies.",
			"Explain sync conflicts and sharing alongside on-prem shares.",
			"Sync loops, full disk from cache, MFA lockouts.",
			"Confirm Internet and account status before rebuilding sync.",
			[2, 3, 4], "res://assets/images/cards/card_growth.png"),
		_part("vpn", "VPN", "Internet and Cloud",
			"Encrypted tunnel for secure remote access to a private network.",
			"Extends LAN resources to remote users across the Internet.",
			"Clients authenticate and encapsulate traffic in tunnels.",
			"Supports remote staff accessing file servers securely.",
			"Failed auth, blocked ports, outdated clients.",
			"Verify base Internet first, then VPN.",
			[2, 3], "res://assets/images/cards/card_network.png"),
		_part("monitor", "Monitor", "Peripherals",
			"Display used to verify POST, BIOS, and OS installation.",
			"Shows video from onboard or discrete GPU outputs.",
			"GPU outputs a signal; panel must select the correct input.",
			"Required for Module 1 BIOS/OS and display troubleshooting.",
			"Wrong input, loose cable, GPU vs board port mismatch.",
			"Try motherboard video on first boot before blaming the GPU.",
			[0, 1, 4], "res://assets/images/cards/card_monitor.png"),
		_part("keyboard_mouse", "Keyboard and Mouse", "Peripherals",
			"Input devices for BIOS setup, OS install, and daily use.",
			"USB or PS/2 HIDs; wireless sets need receivers and power.",
			"HID reports events to the OS; BIOS may need USB support.",
			"Navigate BIOS and create users during OS deployment.",
			"Dead batteries, USB port disabled, sticky keys.",
			"Keep a known-good wired USB keyboard in the toolkit.",
			[1, 4], "res://assets/images/cards/card_input.png"),
		_part("cooling_fan", "Cooling Fan", "Maintenance",
			"Moves air across heatsinks, intakes, and exhausts.",
			"Case and CPU fans regulate temperatures.",
			"PWM/DC control adjusts RPM along an intake-to-exhaust path.",
			"Module 4 PM includes cleaning fans and verifying cooler seating.",
			"Bearing noise, disconnected headers, clogged filters.",
			"Ground yourself before cleaning; avoid spinning fans with vacuum alone.",
			[4], "res://assets/images/cards/card_cooling.png"),
		_part("ups", "UPS", "Maintenance",
			"Battery backup that bridges short outages and softens power events.",
			"Feeds critical gear during brownouts for clean shutdowns.",
			"Inverter supplies AC on failure; surge suppression helps spikes.",
			"Recommended for servers and network closets.",
			"Dead batteries, overloaded VA, ignored beeping.",
			"Size VA for the load; test monthly.",
			[3, 4], "res://assets/images/cards/card_psu.png"),
		_part("thermal_paste", "Thermal Paste", "Maintenance",
			"Thermal interface material between CPU and heatsink.",
			"Fills microscopic gaps for efficient heat transfer.",
			"A thin even layer is enough; excess can spill.",
			"Applied during cooler install and reseating.",
			"Dried paste, no paste on reinstall.",
			"Clean with isopropyl; use a pea-sized amount unless specified.",
			[1, 4], "res://assets/images/cards/card_cooling.png"),
	]


static func filter_parts(query: String, category: String) -> Array[Dictionary]:
	var needle: String = query.strip_edges().to_lower()
	var out: Array[Dictionary] = []
	for part in all_parts():
		if category != ALL and str(part.get("category", "")) != category:
			continue
		if needle == "":
			out.append(part)
			continue
		var blob: String = "%s %s %s %s" % [
			str(part.get("title", "")),
			str(part.get("summary", "")),
			str(part.get("category", "")),
			str(part.get("overview", "")),
		]
		if needle in blob.to_lower():
			out.append(part)
	return out


static func _part(
	id: String,
	title: String,
	category: String,
	summary: String,
	overview: String,
	how_it_works: String,
	css_use: String,
	common_issues: String,
	tips: String,
	modules: Array,
	image_path: String
) -> Dictionary:
	return {
		"id": id,
		"title": title,
		"category": category,
		"summary": summary,
		"overview": overview,
		"how_it_works": how_it_works,
		"css_use": css_use,
		"common_issues": common_issues,
		"technician_tips": tips,
		"related_modules": modules,
		"image": image_path,
	}
